---
title: "The simplest possible N-mixure model"
output: html_notebook
---

The simplest possible N-mixture model from Section 6.3 of
Applied Hierarchical Modeling in Ecology.

```{r}
library(unmarked)
library(rjags)
library(rstan)
options(mc.cores = parallel::detectCores())
library(cmdstanr)
set_cmdstan_path("/usr/local/cmdstan")

lambda <- 2.5 # mean abundance
p <- 0.4      # detection probability
M <- 150      # Number of sites
J <- 2        # Number of replications

set.seed(123)
N <- rpois(M, lambda) # abundance for each site
C <- matrix(0, nrow = M, ncol = J) # count for each site
for (j in 1:J)
  C[, j] <-rbinom(M, N, p)
```

View the genratated data.

```{r}
head(cbind(N, C))
```

## unmarked.

prepare data

```{r}
unmarked_data <- unmarkedFramePCount(y = C)
summary(unmarked_data)
```

fit

```{r}
fit_umk <- pcount(~1 ~1, data = unmarked_data, K = 100)
print(fit_umk)
backTransform(fit_umk, "state")
backTransform(fit_umk, "det")
```

## JAGS

```{r}
jags_data <- list(M = M, J = J, N = N, C = C)
jags_pars <- c("lambda", "p")
jags_model <- jags.model("simplest_N-mixture.txt", data = jags_data, n.chains = 3)
update(jags_model, n.iter = 2000)
fit_jags <- coda.samples(jags_model, jags_pars, n.iter = 2000)
gelman.diag(fit_jags)
summary(fit_jags)
plot(fit_jags)
```

## Stan

### Simple implimentation

```{r}
stan_data <- list(M = M, J = J, K = 100, N = N, C = C)
stan_model1 <- cmdstan_model("simplest_N-mixture1.stan")
fit_stan1 <- stan_model1$sample(data = stan_data,
                                chains = 4, parallel_chains = getOption("mc.cores", 1),
                                iter_warmup = 1000, iter_sampling = 1000,
                                refresh = 500)
fit_stan1$summary()
```

### use reduce_sum

```{r}
stan_data <- list(M = M, J = J, K = 100, N = N, C = C)
stan_model2 <- cmdstan_model("simplest_N-mixture2.stan",
                             cpp_options = list(stan_threads = TRUE))
fit_stan2 <- stan_model2$sample(data = stan_data,
                                chains = 4,
                                parallel_chains = getOption("mc.cores", 1),
                                threads_per_chain = 3,
                                iter_warmup = 1000, iter_sampling = 1000,
                                refresh = 500)
fit_stan2$cmdstan_diagnose()
fit_stan2$summary()
fit_stan2$time()
stanfit2 <- rstan::read_stan_csv(fit_stan2$output_files())
traceplot(stanfit2)
```




